# Generated by Django 4.0.1 on 2022-01-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='365 Item.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_url', models.CharField(default='No payment link.', max_length=250)),
            ],
        ),
    ]
